const pages = [
  {
    id: 1,
    name: "About Me",
    relativeUrl: "about-me",
    bookType: "magicbook",
    region: "topLeft",
    stringLocalize: "about-me",
    imageUrl: null,
    linkButton: null,
  },
  {
    id: 2,
    name: "Skills",
    relativeUrl: "skills",
    bookType: "oldbook1",
    region: "topLeft",
    stringLocalize: "skills",
    imageUrl:
      "https://skillicons.dev/icons?i=git,kubernetes,docker,c,vim&theme=dark",
    linkButton: null,
  },
  {
    id: 3,
    name: "Contacts",
    relativeUrl: "contacts",
    bookType: "oldbook1",
    region: "topLeft",
    stringLocalize: "contacts",
    imageUrl: null,
    linkButton: null,
  },
  {
    id: 4,
    name: "Memories",
    relativeUrl: "project-memories",
    bookType: "book",
    region: "topRight",
    stringLocalize: "project-memories",
    imageUrl: null,
    linkButton: "https://github.com/",
  },
  {
    id: 5,
    name: "Wordle Solver",
    relativeUrl: "project-wordlesolver",
    bookType: "book",
    region: "topRight",
    stringLocalize: "project-wordlesolver",
    imageUrl: null,
    linkButton: null,
  },
  {
    id: 6,
    name: "Resume",
    relativeUrl: "project-resume",
    bookType: "book",
    region: "topRight",
    stringLocalize: "project-resume",
    imageUrl: null,
    linkButton: null,
  },
];

export default pages;
